# Generated by Django 3.2 on 2022-06-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Имя')),
                ('surname', models.CharField(max_length=80, verbose_name='Фамилия')),
                ('age', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Возраст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Customers/%Y/%m/%d', verbose_name='Фото')),
                ('address', models.CharField(max_length=80, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'unique_together': {('name', 'surname')},
            },
        ),
    ]
